# Site settings
title: Squib | A Ruby DSL for prototyping card games
description: >
  Squib is a Ruby DSL for prototyping card and board games.
  Write a little bit of Ruby, define your deck's stats, and you can compile your game into a series of images ready for print-and-play or even print-on-demand.
  Squib is very data-driven and built on the principle of Don't Repeat Yourself.
  Think of it like nanDeck done "the Ruby way". Squib supports:
  A concise set of rules for laying out your cards
  Loading PNGs and SVGs using Cairo
  Complex text rendering using Pango
  Reading xlsx and csv files
  Rendering to individual PNGs or PDF sheets
  Flexible, data-driven layouts in Yaml
  Basic shape drawing
  Unit conversion
  The full power of Ruby!
baseurl: "/squib/" # the subpath of your site, e.g. /blog/
url: "http://andymeneely.github.io/squib" # the base hostname & protocol for your site
twitter_username: andymeneely
github_username:  andymeneely

exclude:
- Gemfile
- Gemfile.lock
- CNAME

include: [ _output ]

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - tables
highlighter: pygments
# highlighter: rouge
